//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RentingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDictionary
    {
        public int did { get; set; }
        public string dkey { get; set; }
        public string dvalue { get; set; }
        public string dvalue2 { get; set; }
        public string dvalue3 { get; set; }
        public string remark { get; set; }
    }
}
