//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RentingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int hid { get; set; }
        public int area { get; set; }
        public int price { get; set; }
        public string pay { get; set; }
        public string unitType { get; set; }
        public string floor { get; set; }
        public string community { get; set; }
        public string pubPerson { get; set; }
        public string time { get; set; }
        public string type { get; set; }
        public string isRecommend { get; set; }
        public string houseDesc { get; set; }
        public string region { get; set; }
        public string state { get; set; }
        public string audit { get; set; }
        public string city { get; set; }
        public string province { get; set; }
    }
}
