//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RentingSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentingSystemEntities : DbContext
    {
        public RentingSystemEntities()
            : base("name=RentingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<HouseMessage> HouseMessage { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserUserInfo> UserUserInfo { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<OrdersUserHouse> OrdersUserHouse { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<UserAuth> UserAuth { get; set; }
        public virtual DbSet<DataDictionary> DataDictionary { get; set; }
    }
}
