//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RentingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuth
    {
        public int uaid { get; set; }
        public string main { get; set; }
        public string users { get; set; }
        public string orders { get; set; }
        public string house { get; set; }
        public string others { get; set; }
        public int uid { get; set; }
    }
}
